package com.kh.mo.shopyapp.utils

object Constants {
    const val CURRENCY_API_BASE_URL = "https://api.currencyfreaks.com/v2.0/"
    const val NOMINATIM_BASE_URL = "https://nominatim.openstreetmap.org/"
    const val collectionPath = "customers"
    const val DRAFT_FAVORITE_ID = "DRAFT_FAVORITE_ID"
    const val DRAFT_CART_ID = "DRAFT_CART_ID"
    const val password = "password"
    const val ErrorEmail = "ErrorEmail"
    const val ErrorPassword = "ErrorPassword"
    const val ErrorRePassword = "ErrorRePassword"
    const val CURRENCY_COLLECTION_ID = "currency_rate"
    const val CURRENCY_DOCUMENT_ID = "CurrencyCollectionID"
    const val ProductInfoFragment = "ProductInfoFragment"
    const val ProductDetailsFragment = "ProductDetailsFragment"
    const val DATA_BASE="DATA_BASE"
    const val PREFERENCE_NAME = "PREFERENCE_NAME"
    const val CUSTOMER_ID = "CUSTOMER_ID"
    const val DRAFT_ID = "DRAFT_ID"
    const val CURRENCY_ID = "currency_id"
    const val USD_ID = "USD"
    const val EGP_ID = "EGP"
    const val EUR_ID = "EUR"
    const val GBP_ID = "GBP"
    const val NO_CART_MESSAGE = "No Cart Found"
    const val ACTION_DELETE = "delete"
    const val ACTION_ADD = "add"
    const val ACTION_SUB = "sub"
}
